// Generated by scripts/sync-battle-presentation-parser.js from the current Web parser.
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.BURST_CONTACT_GAP_MS = void 0;
exports.buildTimeline = buildTimeline;
exports.isInstantBattleEvent = isInstantBattleEvent;
exports.countTimedBattleEvents = countTimedBattleEvents;
exports.readSkillDeclaration = readSkillDeclaration;
exports.collectSkillDescriptions = collectSkillDescriptions;
exports.skillStatusDuration = skillStatusDuration;
exports.skillStatusHitsOpponent = skillStatusHitsOpponent;
exports.isBurstContinuation = isBurstContinuation;
const N = (s) => (s ? parseInt(s.replace(/,/g, ""), 10) : null);
// 真正的暴擊/大成功/完美（驅動全螢幕閃光 + 震動）。
// 注意：💥 是怪物普通攻擊的表情符號（不是暴擊），不可當暴擊判斷。
const CRIT_RE = /會心|致命一擊|弱點命中|完美命中|完美！|要害洞穿|破綻捕捉|大成功/;
// 依日誌文字判斷視覺特效種類（DOT/控制/暴擊…）。順序很重要：先判別獨特關鍵字，
// 最後才落到「裸 ⚡」這類共用符號，避免連擊/大成功被誤判成閃電 DOT。
function detectFx(line, isCrit) {
    // 斬殺（致命收尾用語，與「致命一擊」暴擊區分）
    if (/💀|斬殺|一擊終結|致命收尾|斬落最後|送回老家|毫不留情地帶走/.test(line))
        return "execute";
    // 職業連段先於「🌀＝淨化」判定；殘影亂舞的圖示也是 🌀，但它是攻擊演出。
    if (/殘影亂舞|影襲|連擊氣條|殘影連斬|急速追打|趁勢猛攻|流暢追擊|壓迫連段/.test(line))
        return "combo";
    // 控制 / 狀態
    if (/❄️|🧊|冰凍|結凍/.test(line))
        return "freeze";
    if (/💤|沉睡/.test(line))
        return "sleep";
    if (/😨|恐懼/.test(line))
        return "fear";
    if (/🌿|定身/.test(line))
        return "root";
    if (/🐌|緩速/.test(line))
        return "slow";
    if (/🔇|沉默/.test(line))
        return "silence";
    if (/😵|擊暈|眩暈|失去平衡|身形踉蹌/.test(line))
        return "stun";
    // 淨化 / 光環
    if (/🌀|驅散|淨化|免疫負面/.test(line))
        return "purify";
    if (/光環/.test(line))
        return "aura";
    // DOT（持續傷害）
    if (/☠️|中毒|毒素|淬毒/.test(line))
        return "poison";
    if (/🔥|燒傷|灼燒/.test(line))
        return "burn";
    if (/🩸|流血/.test(line))
        return "bleed";
    if (/🌑|🕯️/.test(line))
        return "curse"; // 只認 emoji;避免怪名(暗影龍/詛咒祭司)讓普通攻擊誤判成詛咒
    if (/閃電|雷電|感電|電擊|震盪|雷擊|麻痺/.test(line))
        return "lightning";
    // 連鎖 / 連擊 / 追擊（ ⚡ 共用符號，放在 lightning 關鍵字之後判斷）
    if (/⛓️|連鎖/.test(line))
        return "chain";
    if (/連擊|追擊|急速追打|殘影連斬|趁勢猛攻|流暢追擊|壓迫連段/.test(line))
        return "combo";
    // 暴擊 / 大成功 / 完美
    if (isCrit || CRIT_RE.test(line))
        return "crit";
    // 格擋 / 盾反（純減傷不算格擋動畫）
    if (/格擋|擋下|盾反|🛡️|舉盾|架住|卸力|硬生生擋下/.test(line))
        return "block";
    if (/符文結界|護盾|護佑|無敵|免疫傷害/.test(line))
        return "block";
    if (/戰意|氣力|計謀|命運|手氣|蓄勢|姿態|血祭|精靈|發動【|職業技能/.test(line))
        return "skill";
    return "hit";
}
// 控制/狀態類（不造成 HP 變化，但要顯示狀態圖示）
const STATUS_FX = new Set(["freeze", "stun", "sleep", "fear", "root", "slow", "silence", "purify", "aura", "block", "execute"]);
/** 把後端 roundLogs（字串陣列）解析成逐回合事件時間軸 */
function buildTimeline(logs, playerName, enemyName, diceEvents = []) {
    const esc = (s) => String(s).replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    const reRem = new RegExp("(" + esc(playerName) + "|" + esc(enemyName) + ")\\s*剩\\s*([\\d,]+)\\s*HP");
    const damageToPlayerRe = new RegExp(`(?:共)?對\\s*(?:你|${esc(playerName)})\\s*造成`);
    const damageToEnemyRe = new RegExp(`(?:共)?對\\s*(?:怪物|${esc(enemyName)})\\s*造成`);
    const inferVisualTarget = (line) => {
        // 技能宣告的「自身」指施放者，不能一律當成玩家。
        if (/(?:發動|施放)【/.test(line)) {
            const caster = line.split(/(?:發動|施放)【/)[0];
            if (caster.includes(enemyName))
                return "enemy";
            if (caster.includes(playerName))
                return "player";
        }
        if (/你受到|你剩|你被|你陷入|你嚇|你無法|你身上|自身|氣條|氣力|戰意|手氣|命運值|計謀值|血祭/.test(line))
            return "player";
        if (line.includes(enemyName) || /怪物剩|怪物/.test(line))
            return "enemy";
        if (line.includes(playerName))
            return "player";
        // 沒寫對象的技能宣告通常是玩家施放；後續傷害／狀態行會再演出受擊方。
        return "player";
    };
    const ev = [];
    let rapidGroupSeq = 0;
    const diceByRound = new Map();
    for (const event of diceEvents || []) {
        const round = Math.max(1, Math.floor(Number(event?.round) || 1));
        const faces = (Array.isArray(event?.faces) ? event.faces : [])
            .map(Number).filter((face) => Number.isInteger(face) && face >= 1 && face <= 6);
        if (!faces.length)
            continue;
        const normalized = {
            round,
            faces,
            initialFaces: Array.isArray(event.initialFaces)
                ? event.initialFaces.map(Number).filter((face) => Number.isInteger(face) && face >= 1 && face <= 6)
                : null,
            rerolledIndices: Array.isArray(event.rerolledIndices)
                ? event.rerolledIndices.map(Number).filter((index) => Number.isInteger(index) && index >= 0 && index < faces.length)
                : [],
            fateFace: Number.isInteger(Number(event.fateFace)) && Number(event.fateFace) >= 1 && Number(event.fateFace) <= 6
                ? Number(event.fateFace)
                : null,
        };
        diceByRound.set(round, [...(diceByRound.get(round) || []), normalized]);
    }
    (logs || []).forEach((rd, ri) => {
        let started = false;
        let activeRound = ri + 1;
        String(rd).split("\n").map((s) => s.trim()).filter(Boolean).forEach((line) => {
            const rn = line.match(/第\s*(\d+)\s*回合/);
            if (rn) {
                activeRound = +rn[1];
                ev.push({ type: "round", round: activeRound, text: "" });
                started = true;
                return;
            }
            if (/^[─—-]+$/.test(line))
                return;
            if (!started) {
                ev.push({ type: "round", round: ri + 1, text: "" });
                started = true;
            }
            const clean = line.replace(/\*\*/g, "");
            const dmg = line.match(/(?:造成|轟出)\s*\*?\*?([\d,]+)\*?\*?\s*(?:點\s*)?傷害|(?:造成|轟出)\s*\*?\*?([\d,]+)\*?\*?\s*點|(?:受到|仍受到|承受|代承)\s*\*?\*?([\d,]+)\*?\*?\s*點|傷害降至\s*\*?\*?([\d,]+)\*?\*?/);
            const heal = line.match(/(?:回復|恢復)\s*\*?\*?([\d,]+)\*?\*?\s*HP/);
            const rem = line.match(reRem);
            // 任何「…剩 X HP」都抓得到剩餘血量（含「你剩」「怪物剩」literal）
            const remAny = line.match(/剩\s*([\d,]+)\s*(?:\/\s*[\d,]+\s*)?HP/);
            const crit = CRIT_RE.test(line);
            // 骰子武器：動畫使用後端結構化骰面；舊回應才從同一條後端戰報降級解析。
            // 事件插在實際傷害之前，播放器會等骰面落定才繼續跳傷害數字。
            if (/^🎲.*擲出/.test(clean)) {
                const structured = diceByRound.get(activeRound)?.shift();
                const fallbackFaces = [...clean.matchAll(/【([1-6])】/g)].map((matched) => Number(matched[1]));
                const dice = structured || (fallbackFaces.length ? { round: activeRound, faces: fallbackFaces } : null);
                if (dice) {
                    ev.push({ type: "dice", target: "enemy", fx: "skill", text: clean, dice });
                    return;
                }
            }
            // 怪物大型多段攻擊仍逐段演出，但標記成同一 rapidGroup；
            // 播放器會把傷害／格擋／閃避全部快速塞進本回合固定 AGI 時槽，不延長回合。
            const monsterMulti = clean.match(/(\d+)\s*段連襲共\s*([\d,]+)\s*（(.+?)｜(你剩|精靈剩)\s*([\d,]+)/);
            if (monsterMulti) {
                const rawParts = monsterMulti[3].split(/[＋+]/);
                const damagePartIndexes = rawParts
                    .map((part, index) => /[\d,]+/.test(part) && !/閃避|揮空/.test(part) ? index : -1)
                    .filter((index) => index >= 0);
                const lastDamageIndex = damagePartIndexes.at(-1) ?? -1;
                const rapidGroup = `monster-multi-${rapidGroupSeq++}`;
                rawParts.forEach((part, index) => {
                    const rapidMeta = { rapidGroup, rapidIndex: index + 1, rapidTotal: rawParts.length };
                    if (/閃避|揮空/.test(part)) {
                        ev.push({ type: "miss", target: "player", fx: "dodge", text: index === 0 ? clean : "", ...rapidMeta });
                        return;
                    }
                    const value = N(part.match(/[\d,]+/)?.[0] || null);
                    if (value == null)
                        return;
                    const blocked = /🛡️|盾/.test(part);
                    const spirit = /☀️/.test(part);
                    ev.push({
                        type: "hit",
                        target: spirit || monsterMulti[4] === "精靈剩" ? "spirit" : "player",
                        value,
                        hp: index === lastDamageIndex ? N(monsterMulti[5]) : null,
                        crit: crit && index === damagePartIndexes[0],
                        fx: blocked ? "block" : spirit ? "aura" : crit && index === damagePartIndexes[0] ? "crit" : "hit",
                        text: index === 0 ? clean : "",
                        ...rapidMeta,
                    });
                });
                return;
            }
            // 合併連擊戰報（含影舞者「殘影亂舞」）拆回逐段快速攻擊。
            // 每段傷害都會跳出，最後一段才套精準 HP；整組仍受該回合固定時間上限約束。
            const comboSummary = clean.match(/(\d+)\s*連擊[：:]\s*(.+?)\s*[＝=]\s*([\d,]+)/);
            if (comboSummary) {
                const segmentValues = comboSummary[2]
                    .split(/[＋+]/)
                    .map((part) => N(part.match(/[\d,]+/)?.[0] || null))
                    .filter((value) => value != null && value >= 0);
                const rapidGroup = `player-combo-${rapidGroupSeq++}`;
                segmentValues.forEach((value, index) => {
                    ev.push({
                        type: "hit",
                        target: "enemy",
                        value,
                        hp: index === segmentValues.length - 1 && remAny ? N(remAny[1]) : null,
                        crit: false,
                        fx: "combo",
                        text: index === 0 ? clean : "",
                        comboN: index > 0 ? index + 1 : undefined,
                        rapidGroup,
                        rapidIndex: index + 1,
                        rapidTotal: segmentValues.length,
                    });
                });
                return;
            }
            // 受傷者判定：「你受到/你剩」=玩家；「怪物剩/${enemyName} 剩/對 ${enemyName}」=怪物
            const hitsPlayer = damageToPlayerRe.test(clean)
                || /你受到|你剩|仍受到|的攻擊被格擋|攻勢沉重|日之精靈代承/.test(clean)
                || (clean.includes(playerName) && /受到/.test(clean));
            const hitsEnemy = damageToEnemyRe.test(clean)
                || /怪物剩/.test(clean)
                || (rem && rem[1] === enemyName);
            if (heal) {
                // 回復對象：怪物生命回復（生命力逐漸/怪物剩）vs 玩家回復（你/你剩）
                const target = /日之精靈|精靈剩/.test(line)
                    ? "spirit"
                    : (/怪物剩|生命力逐漸/.test(line) || (rem && rem[1] === enemyName) || (line.includes(enemyName) && !/你/.test(line))) ? "enemy" : "player";
                const spiritRem = line.match(/精靈剩?\s*([\d,]+)\s*\/\s*([\d,]+)/);
                ev.push({
                    type: "heal",
                    target,
                    value: N(heal[1]),
                    text: clean,
                    hp: spiritRem ? N(spiritRem[1]) : remAny ? N(remAny[1]) : null,
                    maxHp: spiritRem ? N(spiritRem[2]) : null,
                    fx: "heal"
                });
                return;
            }
            if (dmg) {
                const dmgVal = N(dmg.slice(1).find(Boolean) || null);
                let target;
                const spiritRem = line.match(/精靈剩?\s*([\d,]+)\s*\/\s*([\d,]+)/);
                if (/日之精靈代承|精靈剩/.test(clean))
                    target = "spirit";
                else if (rem)
                    target = rem[1] === playerName ? "player" : "enemy";
                else if (hitsPlayer)
                    target = "player";
                else if (hitsEnemy)
                    target = "enemy";
                else
                    target = line.includes(playerName) && !line.includes(enemyName) ? "player" : "enemy";
                const hp = spiritRem ? N(spiritRem[1]) : remAny ? N(remAny[1]) : null; // 抓「你剩/怪物剩/精靈剩 X HP」精準血量
                const hitFx = detectFx(line, crit);
                let comboN;
                if (hitFx === "combo") {
                    // 戰報連擊標籤：第1段=「連擊」(無數字)、第2段=「2 連擊」…；主擊算第1擊 → 顯示段數 = 標籤數+1
                    const m = line.match(/(\d+)\s*連擊/);
                    comboN = (m ? parseInt(m[1], 10) : 1) + 1;
                }
                ev.push({ type: "hit", target, value: dmgVal, hp, maxHp: spiritRem ? N(spiritRem[2]) : null, crit, fx: hitFx, text: clean, comboN });
                return;
            }
            if (!/(?:發動|施放)【/.test(clean) && /未命中|閃避|閃過|避開|閃開|躲過|落空|揮空|撲了個空|構不到|無法反擊|MISS|手滑/.test(line)) {
                const playerAttackMiss = /你的攻擊|連擊被閃開|閃避後出箭|你(?:的)?(?:攻擊|反擊|揮|斬|射|手滑)/.test(line)
                    || (clean.startsWith("💨") && clean.includes(enemyName) && !/你.*(?:躲過|避開|閃過)/.test(clean));
                ev.push({ type: "miss", target: playerAttackMiss ? "enemy" : "player", fx: "dodge", text: clean });
                return;
            }
            // 純狀態（控制/淨化/光環）：顯示狀態圖示，不改 HP
            const sfx = detectFx(line, false);
            const skillDeclaration = clean.match(/^(.*?)\s*(?:發動|施放)【([^】]+)】/);
            if (skillDeclaration) {
                const caster = skillDeclaration[1].includes(enemyName) ? "enemy" : "player";
                ev.push({ type: "info", target: caster, fx: "skill", text: clean });
                return;
            }
            if (STATUS_FX.has(sfx)) {
                const target = inferVisualTarget(line);
                ev.push({ type: "status", target, fx: sfx, text: clean });
                return;
            }
            // 每一條有效戰報都要有畫面：無法分類的純敘述落到通用技能光效，不再靜默。
            ev.push({ type: "info", target: inferVisualTarget(line), fx: sfx === "hit" ? "skill" : sfx, text: clean });
        });
    });
    return ev;
}
/** Text and status updates share the current action; only actual actions use a playback slot. */
function isInstantBattleEvent(event) {
    return event.type === "info" || event.type === "status";
}
function countTimedBattleEvents(events) {
    return events.filter((event) => event.type !== "dice" && !isInstantBattleEvent(event)).length;
}
function readSkillDeclaration(text) {
    const match = String(text || "").match(/(?:發動|施放)【([^】]+)】[！!]?(.*)/);
    return match ? { name: match[1].trim(), description: match[2].trim() } : null;
}
/** Keep the first effect text for the entire encounter, even after its status expires. */
function collectSkillDescriptions(events) {
    const descriptions = new Map();
    for (const event of events) {
        const declaration = readSkillDeclaration(event.text || "");
        if (declaration?.description) {
            const key = `${event.target === "enemy" ? "enemy" : "player"}:${declaration.name}`;
            if (!descriptions.has(key))
                descriptions.set(key, declaration.description);
        }
    }
    return descriptions;
}
function skillStatusDuration(text) {
    const turns = String(text || "").match(/持續\s*(\d+)\s*回合/);
    return Math.max(1, Math.min(20, Number(turns?.[1]) || 1));
}
function skillStatusHitsOpponent(description) {
    return /敵方|對手|目標|你(?:的|身上)?/.test(description) && !/自身|自己/.test(description);
}
/** A combo is one swing with distinct, tightly spaced contacts. */
exports.BURST_CONTACT_GAP_MS = 70;
function isBurstContinuation(previous, next) {
    if (!previous || !next || previous.target !== next.target)
        return false;
    const contact = (event) => event.type === "hit" || event.type === "miss";
    if (!contact(previous) || !contact(next))
        return false;
    return Boolean(previous.rapidGroup && previous.rapidGroup === next.rapidGroup)
        || Number(next.comboN) > 1 || next.fx === "combo";
}
